spring:
  config:
    activate:
      on-profile:
        - secret

  datasource:
    url: jdbc:mysql://blog-db:6633/blog-db
    #url: jdbc:mysql://localhost:6633/blog-db
    username: root
    password: '0000'

aws:
  s3:
    url: "https://resource.stopthe.world"
    region: "ap-northeast-2"
    bucket: "birariro-blog-resource"
    path: "blog/image/"
  key:
    access: ENC(FHp1TQOdhXX+o6tU9XUQjuESZpeX8DqWdpxbDIiiv+E==)
    secret: ENC(GrFUJTaMbPwPGtUaEMyq74FHtZwrLNe9z3P/2tscVNCC5xm2MSAsEjAP1iHZ4Y7txktUIBIY67c=)


jasypt:
  encryptor:
    key: ${jasypt}
    algorithm: PBEWithMD5AndDES

jwt:
  secret: ENC(Q57yFsEBAdMMhAObbFs5dglwPwNGz5NIZXXDkgQ5E3hoFbAlBZAgFk2v9Gf6Q0ZhLENDPIuo7K1vDkdGlMeP3sSYz9PhByBAFmRPwpno3C1p7cpXn6rBVSHSCSYgL/pNVRV5gTZQAul6D2gdO6wbNDyIrVap8ch2fRczzVuJJXLgEfB+q7HvYxjjLDkxO5U6)
  expiration: 60



