spring:
  profiles:
    active: prod
    group:
      test:
        - secret-demo
        - common
        - testcontainers
      demo:
        - secret-demo
        - common
      prod:
        - secret
        - common
