spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=MariaDB
    driverClassName: org.h2.Driver
    username: sa
    password:


logging:
  level:
    ROOT: INFO
    org.hibernate: TRACE
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.orm: TRACE
    org.springframework.transaction: TRACE
    com.mysql.cj.jdbc: TRACE
