aws:
  s3:
    region: "ap-northeast-2"
    bucket: "image-storage"
    path: "/blog/image"
  key:
    access: "access-key"
    secret: "secret-key"

jasypt:
  encryptor:
    key: \${jasypt:nokey}
    algorithm: PBEWithMD5AndDES