spring:
  config:
    activate:
      on-profile:
        - secret-demo
  datasource:
    url: jdbc:mysql://localhost:6633/blog-db
    username: root
    password: '0000'
aws:
  s3:
    url: "https://resource.stopthe.world"
    region: "ap-northeast-2"
    bucket: "image-storage"
    path: "blog/image/"
  key:
    access: "access-key"
    secret: "secret-key"

jasypt:
  encryptor:
    key: TestKey
    algorithm: PBEWithMD5AndDES

jwt:
  secret: TestKeyTestKeyTestKeyTestKeyTestKeyTestKeyTestKeyTestKeyTestKeyTestKeyTestKeyTestKeyTestKeyTestKeyTestKeyTestKeyTestKeyTestKeyTestKeyTestKeyTestKeyTestKeyTestKeyTestKeyTestKeyTestKeyTestKeyTestKey
  expiration: 60
