spring:
  config:
    activate:
      on-profile:
        - secret-demo
aws:
  s3:
    region: "ap-northeast-2"
    bucket: "image-storage"
    path: "/blog/image/"
  key:
    access: "access-key"
    secret: "secret-key"

jasypt:
  encryptor:
    key: TestKey
    algorithm: PBEWithMD5AndDES

jwt:
  secret: TestKeyTestKeyTestKeyTestKeyTestKeyTestKeyTestKeyTestKeyTestKeyTestKeyTestKeyTestKeyTestKeyTestKeyTestKeyTestKeyTestKeyTestKeyTestKeyTestKeyTestKeyTestKeyTestKeyTestKeyTestKeyTestKeyTestKeyTestKey
  expiration: 60
