version: '3'

services:
  dynamodb-local:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - dynamodb_data:/data
    command: "-jar DynamoDBLocal.jar -inMemory -sharedDb"
    networks:
      - dynamodb-network

volumes:
  dynamodb_data:

networks:
  dynamodb-network:
    driver: bridge
