name: sync notion-db to dynamo-db

on:
  schedule:
    - cron: '0 0 * * *'  # 매일 자정(UTC 00:00)
  workflow_dispatch:

jobs:
  get_request_job:
    runs-on: ubuntu-latest

    steps:
      - name: Send GET request to API
        run: |
          curl -X GET ${{ secrets.AWS_SYNC_API_GATEWAY_URL }}
