name: Scheduled GET Request

on:
  schedule:
    # 매일 자정(UTC 00:00)에 실행
    - cron: '0 0 * * *'

jobs:
  get_request_job:
    runs-on: ubuntu-latest

    steps:
      - name: Send GET request to API
        run: |
          curl -X GET ${{ secrets.AWS_SYNC_API_GATEWAY_URL }}
