name: build with docker upload

on:
  push:
    branches: [ main ]

jobs:

  build:
    if: ${{ !contains(github.event.head_commit.message, '[skip]') }}
    runs-on: ubuntu-latest

    steps:
      - name: greeting
        run: echo Run CI

      - name: checkout depoly branch
        uses: actions/checkout@v4

      - name: setup JAVA 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: grant executive permission to Gradlew
        run: chmod +x gradlew

      - name: build jar
        run: ./gradlew clean build --exclude-task test

      - name: pipeline upload jar
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: ./build

      - name: pipeline upload dockerfile
        uses: actions/upload-artifact@v1
        with:
          name: dockerfile
          path: ./share/ci/Dockerfile

  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:

      - name: pipeline download jar
        uses: actions/download-artifact@v1
        with:
          name: build

      - name: pipeline download dockerfile
        uses: actions/download-artifact@v1
        with:
          name: dockerfile

      - name: echo build/libs dir
        run: ls -al ./build/libs

      - name: move dockerfile
        run: mv dockerfile/Dockerfile .

      - name: Docker Image Build
        run: docker build -t ${{ secrets.DOCKER_HUB_ID }}/${{ secrets.DOCKER_HUB_REPOSITORY }} .

      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_ID }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Push Docker Image From DockerHub
        run: docker push ${{ secrets.DOCKER_HUB_ID }}/${{ secrets.DOCKER_HUB_REPOSITORY }}

#  deploy:
#    needs: docker
#    runs-on: ubuntu-latest
#    steps:
#      - name: deploy start
#        run: echo deploy start
#      - name: deploy server accessq
#        uses: appleboy/ssh-action@v0.1.6
#        with:
#          host: ${{ secrets.WAS_HOST }}
#          username: ${{ secrets.WAS_USERNAME }}
#          password: ${{ secrets.WAS_PASSWORD }}
#          port: ${{ secrets.WAS_SSH_PORT }}
#          script: |
#            docker stop blog
#            docker rm blog
#            docker pull ${{ secrets.DOCKER_HUB_ID }}/${{ secrets.DOCKER_HUB_REPOSITORY }}
#            docker run -d -p 8791:8791 --name blog ${{ secrets.DOCKER_HUB_ID }}/${{ secrets.DOCKER_HUB_REPOSITORY }}